'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {PlayerProfile} from './player-profile';
import { useState,useEffect,useMemo,useRef,type ReactNode,type CSSProperties } from 'react';
import { Activity,ArrowDown,ArrowUp,ArrowRight,ArrowUpRight,BarChart3,Check,ChevronLeft,ChevronRight,ChevronsRight,ChevronDown,CircleHelp,ClipboardList,Banknote,Globe2,Handshake,House,LoaderCircle,Play,RotateCcw,Search,Shield,SlidersHorizontal,Sparkles,Target,Trophy,UserRound,Users,Wallet,X,CalendarDays,MessageSquare,Save,CircleDot as Baseball,GraduationCap,ExternalLink } from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {WorldProvider,useWorld} from './world-context';
import type {WorldCatalog,Club,FinanceEntry} from '../../packages/shared/src/types';
import {type GameState,type Player,type Result,type Coach,overall,money,toManwon,fromManwon,lineupAuto,askPrice,coachRoles,coachSkill,teamBudget} from '../../packages/shared/src/game-view';
import {isUnrated,ratingText,potentialText} from '../../packages/shared/src/ratings';
import {Mood,InboxPanel,DynamicsPanel,OutgoingTransferPanel} from './club-panels';
import {SchedulePanel} from './schedule-panel';
import {dateLabel} from '../../packages/shared/src/calendar';
import {StadiumReplay,LiveMatchScreen} from './stadium-replay';
import {TacticalBoard,DefensiveField,ReservePanel,CoachPanel,PositionTraining} from './management-panels';
import {dayLabel,firstTeam,preseasonFixtures,transfersBlocked} from '../../packages/shared/src/management';
type Act=(action:Record<string,unknown>)=>Promise<GameState|null>;
const nav=[{id:'home',label:'홈',icon:House},{id:'inbox',label:'수신함',icon:MessageSquare},{id:'dynamics',label:'선수단 분위기',icon:Activity},{id:'squad',label:'선수단',icon:Users},{id:'reserves',label:'2군 · 육성',icon:GraduationCap},{id:'tactics',label:'전술 · 타순',icon:ClipboardList},{id:'schedule',label:'일정 · 결과',icon:CalendarDays},{id:'world',label:'리그 · 세계',icon:Globe2},{id:'market',label:'영입 · 이적',icon:ArrowUpRight},{id:'agents',label:'에이전트',icon:Handshake},{id:'staff',label:'코치 · 훈련',icon:GraduationCap},{id:'finance',label:'구단 재정',icon:Wallet}];
const tactics=[['balanced','균형 잡힌 야구','타격과 출루의 균형'],['power','장타 중심','장타 확률 증가 · 삼진 위험'],['smallball','기동력 야구','빠른 주자의 적극적인 도루'],['patient','선구안 중심','볼넷과 출루 기회 증가']];
const trainings=[['balanced','균형 훈련','타자는 컨택, 투수는 구위'],['power','타격 집중','장타력 중심의 타격 훈련'],['pitching','투수 집중','구위와 투구 완성도'],['defense','수비 집중','수비 기본기 강화'],['rest','회복 중심','성장 대신 컨디션 회복']];
const positions:Record<string,string>={P:'투수',C:'포수',IF:'내야수',OF:'외야수',DH:'지명타자'};
function Badge({club,size='normal'}:{club:Club;size?:string}){return <span className={`club-badge ${size}`} style={{'--club':club.color} as CSSProperties}>{club.short}</span>}
function Rating({value,player}:{value:number;player?:Player}){if(player&&isUnrated(player))return <span className="muted tiny">미평가</span>;return <span className={`rating ${value>=85?'elite':value>=70?'good':''}`}>{Math.round(value)}{player?.rating?.status==='provisional'&&'*'}</span>}
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="select" aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function Metric({label,value,sub,icon}:{label:string;value:ReactNode;sub:ReactNode;icon?:ReactNode}){return <div className="metric"><div className="metric-top">{label}{icon}</div><div className="metric-value">{value}</div><div className="muted">{sub}</div></div>}
function SectionTitle({title,eyebrow,children}:{title:string;eyebrow?:string;children?:ReactNode}){return <div className="section-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{children}</div>}
function PlayerName({p,onClick}:{p:Player;onClick?:(p:Player)=>void}){return <button className="player-name" onClick={()=>onClick?.(p)}><span className={`player-avatar ${p.real?'':'generated'}`}>{p.number}</span><span><strong>{p.name}</strong><small>{positions[p.pos]} <span className={p.real?'real-tag':'gen-tag'}>{p.real?'실명':'가상'}</span></small></span></button>}
function AppSidebar({g,view,onView,onNew}:{g:GameState;view:string;onView:(v:string)=>void;onNew:()=>void}){
 const {getClub,getLeague}=useWorld();const {setOpenMobile}=useSidebar();const club=getClub(g.club);
 const groups=[{label:'구단',ids:['home','inbox','squad','dynamics','reserves','tactics']},{label:'대회',ids:['schedule','world']},{label:'운영',ids:['market','agents','staff','finance']}];
 return <Sidebar className="app-sidebar">
  <SidebarHeader><div className="brand"><Baseball/><span>DUGOUT<i>BASEBALL MANAGEMENT</i></span><b className="edition-number">26</b></div>
   <div className="sidebar-club" style={{'--club':club.color} as CSSProperties}><Badge club={club}/><span><strong>{club.name}</strong><small>{getLeague(club.league).name} · {g.year}</small></span></div>
  </SidebarHeader>
  <SidebarContent>{groups.map(group=><SidebarGroup key={group.label}><SidebarGroupLabel>{group.label}</SidebarGroupLabel><SidebarMenu>{group.ids.map(id=>{const n=nav.find(n=>n.id===id)!;return <SidebarMenuItem key={id}><SidebarMenuButton className="nav-button" isActive={view===id} onClick={()=>{onView(id);setOpenMobile(false)}}><n.icon/><span>{n.label}</span>{id==='agents'&&g.deals.length>0&&<b className="nav-count">{g.deals.length}</b>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroup>)}</SidebarContent>
  <SidebarFooter><button className="new-career" onClick={onNew}><RotateCcw size={14}/>새 커리어</button><div className="manager"><span className="manager-avatar"><UserRound size={18}/></span><span><strong>{g.manager}</strong><small>감독 · 평판 {g.reputation}</small></span></div></SidebarFooter>
 </Sidebar>;
}
function GameScreen({initial,refreshCatalog,initialPlayerId,initialView}:{initial:CareerData;refreshCatalog:()=>Promise<void>;initialPlayerId?:string;initialView?:string}){const {clubs,leagues,getClub,getLeague,nextFixture,catalogVersion,marketPlayers}=useWorld();const router=useRouter();const view=initialPlayerId?'player':nav.some(n=>n.id===initialView)?initialView!: 'home';const setView=(id:string)=>router.push('/?view='+encodeURIComponent(id));const setPlayer=(p:Player)=>router.push('/players/'+encodeURIComponent(p.id)+'?from='+encodeURIComponent(view));const [g,setG]=useState<GameState|null>(initial.state),[revision,setRevision]=useState(initial.revision),[loading,setLoading]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[newConfirm,setNewConfirm]=useState(false),[replay,setReplay]=useState<Result|null>(null),[help,setHelp]=useState(false);const locked=useRef(false);const [ledger,setLedger]=useState(initial.ledger);
 async function load(){setLoading(true);setError('');try{const res=await fetch('/api/career',{cache:'no-store'});const d=await res.json();if(!res.ok)throw new Error(d.error||'커리어를 불러오지 못했습니다.');setG(d.state);setRevision(d.revision);setLedger(d.ledger||[]);}catch(e){setError(e instanceof Error?e.message:'연결하지 못했습니다.');}finally{setLoading(false)}}
 const act:Act=async action=>{if(locked.current)return null;locked.current=true;setBusy(true);try{const res=await fetch('/api/career',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,revision,requestId:crypto.randomUUID()})});const d=await res.json();if(!res.ok){if(res.status===409&&'state'in d){setG(d.state);setRevision(d.revision);setLedger(d.ledger||[]);}throw new Error(d.error||d.message||'요청을 처리하지 못했습니다.');}setG(d.state);setRevision(d.revision);setLedger(d.ledger||[]);return d.state;}catch(e){toast.error(e instanceof Error?e.message:'저장하지 못했습니다.');return null;}finally{locked.current=false;setBusy(false)}};
 async function openReplay(result:Result){if(result.log.length){setReplay(result);return;}try{const res=await fetch('/api/career/matches/'+encodeURIComponent(result.id),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error);setReplay(data);}catch{toast.error('경기 기록을 불러오지 못했습니다. 다시 시도해 주세요.');}}
 async function simulate(count=1,watch=false){if(g?.liveMatch)return;if(count===1&&watch&&g&&nextFixture(g)){await act({type:'startMatch'});return;}const next=await act(count===1?{type:'continue'}:{type:'advance',count});if(next)toast.success(`${Math.max(1,next.day-(g?.day||0))}일 진행했습니다.`);}
 if(!g||setup)return <><NewCareer loading={loading} error={error} retry={load} busy={busy} existing={!!g} cancel={()=>setSetup(false)} onStart={async(club,manager,mode,firstSeasonTransferBan,revealPotential)=>{const result=await act({type:'start',club,manager,mode,firstSeasonTransferBan,revealPotential,replace:!!g});if(result){await refreshCatalog();setSetup(false);setView('home');toast.success(`${getClub(club).name}의 감독으로 취임했습니다.`)}}}/><Toaster theme="dark" position="bottom-right"/></>;
 const club=getClub(g.club),league=getLeague(club.league);const pending=busy;const selectedPlayer=initialPlayerId?(g.roster.find(p=>p.id===initialPlayerId)||marketPlayers(g).find(p=>p.id===initialPlayerId)):undefined;
 return <SidebarProvider style={{'--sidebar-width':'204px'} as CSSProperties}><AppSidebar g={g} view={view} onView={setView} onNew={()=>setNewConfirm(true)}/>
 <main className="workspace"><header className="topbar">
  <div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><Badge club={club} size="small"/><div><strong>{club.name}</strong><span>{league.name}<ChevronRight size={11}/>{(view==='player'?'선수 상세':nav.find(n=>n.id===view)?.label)}</span></div></div>
  <div className="topbar-right"><span className="save-state" aria-live="polite">{pending?<LoaderCircle className="spin" size={12}/>:<Check size={12}/>} {pending?'저장 중':'저장됨'}</span><button className="icon-button" aria-label="게임 안내" onClick={()=>setHelp(true)}><CircleHelp size={18}/></button><div className="date"><b>{g.year} 시즌</b><span>{g.phase==='preseason'?dateLabel(g):g.phase==='regular'?`${dateLabel(g)} · 정규 시즌`:g.phase==='semifinal'?'플레이오프 · 준결승':g.phase==='final'?'플레이오프 · 결승':'시즌 종료'}</span></div>
   <div className="page-actions">{g.phase!=='finished'?<><button className="button secondary compact advance-week" disabled={busy} onClick={()=>simulate(7)} title="7일 진행"><ChevronsRight size={15}/><span>7일</span></button><button className="button primary continue-button" disabled={busy} onClick={()=>simulate(1,true)}>{busy?<LoaderCircle size={16} className="spin"/>:<><span>{nextFixture(g)?'경기 진행':'계속 진행'}</span><ChevronRight size={18}/></>}</button></>:<button className="button primary continue-button" disabled={busy} onClick={()=>act({type:'nextSeason'})}>다음 시즌<ChevronRight size={18}/></button>}</div>
  </div></header>
  <div className="context-bar"><div className="context-title">{(view==='player'?'선수 상세':nav.find(n=>n.id===view)?.label)}</div><nav aria-label="구단 바로가기">{[{id:'home',label:'개요'},{id:'squad',label:'선수단'},{id:'schedule',label:'일정'},{id:'finance',label:'재정'}].map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>setView(n.id)}>{n.label}</button>)}</nav><span>{league.label} · {club.city}</span></div>
  <div className="workspace-body">{g.news.some(n=>n.choiceKind&&!n.choice)&&<div className="decision-banner"><span>감독의 답변을 기다리는 선수 면담이 있습니다.</span><button className="text-button" onClick={()=>setView('inbox')}>수신함에서 확인 →</button></div>}{g.catalogVersion!==catalogVersion&&<div className="preseason-banner"><strong>선수·코치 DB 업데이트</strong><span>현재 계약과 시즌 기록을 유지하며 누락 선수를 추가합니다.</span><button disabled={busy} onClick={()=>act({type:'syncCatalog'})}>새 명단 반영 →</button></div>}{g.phase==='preseason'&&<div className="preseason-banner"><strong>정규시즌 개막까지 {-g.day}일</strong><span>전술 숙련도 {Math.round(g.tacticFamiliarity??55)}% · 연습경기 {g.history.filter(r=>r.friendly).length}/4회</span><button onClick={()=>setView('tactics')}>전술 준비 →</button></div>}<div className="page-title"><h1>{view==='home'?'감독 사무실':(view==='player'?'선수 상세':nav.find(n=>n.id===view)?.label)}</h1><p>{view==='home'?`${g.manager} · ${club.name}`:view==='squad'?`${g.roster.length}명 등록`:view==='agents'?`${g.deals.length}건의 협상`:view==='staff'?`${g.staff.length}명의 코칭 스태프`:league.name}</p></div>
 {view==='player'&&<><Link className="text-button player-back" href={'/?view='+encodeURIComponent(nav.some(n=>n.id===initialView)?initialView!:'squad')}>← 목록으로</Link>{selectedPlayer?<PlayerProfile key={selectedPlayer.id} player={selectedPlayer} game={g} act={act} busy={busy}/>:<section className="panel panel-content"><h2>선수를 찾을 수 없습니다</h2><p>이 커리어에 없거나 더 이상 조회할 수 없는 선수입니다.</p><Link href="/?view=squad">선수단으로</Link></section>}</>}
 {view==='home'&&<Dashboard g={g} setView={setView} simulate={()=>simulate(1,true)} act={act} busy={busy} onPlayer={setPlayer} replay={openReplay}/>}
 {view==='inbox'&&<InboxPanel g={g} act={act} busy={busy} onPlayer={setPlayer}/>}
 {view==='dynamics'&&<DynamicsPanel g={g} onPlayer={setPlayer}/>}
 {view==='squad'&&<Squad g={g} onPlayer={setPlayer}/>}
 {view==='reserves'&&<ReservePanel g={g} act={act} busy={busy} onPlayer={setPlayer}/>}
 {view==='tactics'&&<TacticalBoard g={g} act={act} busy={busy} onPlayer={setPlayer}/>}
 {view==='schedule'&&<SchedulePanel g={g} replay={openReplay}/>}
 {view==='world'&&<World g={g} onPlayer={setPlayer}/>}
 {view==='market'&&<Market g={g} onPlayer={setPlayer}/>}
 {view==='agents'&&<Agents g={g} act={act} busy={busy} onPlayer={setPlayer}/>}
 {view==='staff'&&<CoachPanel g={g} act={act} busy={busy}/>}
 {view==='finance'&&<Finance g={g} ledger={ledger}/>}
 </div><footer className="game-footer"><span>DUGOUT <b>2026</b> · {leagues.length} 리그 · {clubs.length} 구단</span><button onClick={()=>setHelp(true)}>게임 규칙 · 데이터 안내 <ArrowUpRight size={13}/></button></footer></main>
 <>{g.liveMatch&&<LiveMatchScreen g={g} act={act} busy={busy}/>}</><StadiumReplay result={replay} close={()=>setReplay(null)}/><Help open={help} close={()=>setHelp(false)}/>
 <AlertDialog open={newConfirm} onOpenChange={setNewConfirm}><AlertDialogContent className="confirm-dialog"><AlertDialogHeader><AlertDialogTitle>새 구단에서 시작할까요?</AlertDialogTitle><AlertDialogDescription>새 커리어를 최종 시작하면 현재 커리어의 선수·계약·시즌 기록이 교체됩니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><AlertDialogAction onClick={()=>setSetup(true)}>구단 선택으로</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster theme="dark" position="bottom-right"/></SidebarProvider>;
}
function NewCareer({loading,error,retry,busy,onStart,existing,cancel}:{loading:boolean;error:string;retry:()=>void;busy:boolean;onStart:(c:string,m:string,mode:string,ban:boolean,reveal:boolean)=>void;existing:boolean;cancel:()=>void}){
 const {clubs,leagues,getClub,getLeague,baseRoster}=useWorld();const [lid,setLid]=useState('kbo'),[cid,setCid]=useState('kbo-lg'),[manager,setManager]=useState('강경원'),[region,setRegion]=useState('전체'),[mode,setMode]=useState('short'),[ban,setBan]=useState(false),[reveal,setReveal]=useState(false),[help,setHelp]=useState(false);
 const l=getLeague(lid),c=getClub(cid),roster=useMemo(()=>baseRoster(cid),[cid,baseRoster]);const featured=[...roster].sort((a,b)=>overall(b)-overall(a)).slice(0,5);
 return <div className="setup-page"><header className="setup-header"><div className="brand"><Baseball/><span>DUGOUT<i>BASEBALL MANAGEMENT</i></span><b className="edition-number">26</b></div><div className="setup-header-right"><span>새 커리어</span><button className="icon-button" aria-label="게임 안내" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button>{existing&&<button className="button secondary compact" onClick={cancel}>기존 커리어로</button>}</div></header>
 <main className="setup-main"><div className="setup-heading"><div><h1>구단 선택</h1><p>운영할 리그와 구단을 선택하세요.</p></div><div className="setup-steps"><span className="current">01 리그</span><ChevronRight size={13}/><span>02 구단</span><ChevronRight size={13}/><span>03 감독 취임</span></div></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={retry}>다시 불러오기</button></div>}
 <div className="setup-grid"><section className="world-selector"><div className="selector-heading"><h2>리그</h2><span>{leagues.length}개 대회</span></div><div className="region-filter"><Choice value={region} onChange={setRegion} label="대륙" items={['전체','아시아','아메리카','유럽','오세아니아'].map(t=>({value:t,label:t==='전체'?'모든 대륙':t}))}/></div>
 <div className="league-grid">{leagues.filter(v=>region==='전체'||v.region===region).map(v=><button className={`league-card ${v.id===lid?'selected':''}`} key={v.id} aria-pressed={v.id===lid} onClick={()=>{setLid(v.id);setCid(clubs.find(c=>c.league===v.id)!.id)}}><span className="flag">{v.flag}</span><span><strong>{v.name}</strong><small>{v.country}</small></span><span className="league-count">{clubs.filter(c=>c.league===v.id).length}</span>{v.id===lid&&<Check size={13}/>}</button>)}</div></section>
 <section className="club-browser"><div className="selector-heading"><h2>{l.name}</h2><span>{l.country} · {l.season}</span></div><div className="club-list-head"><span>구단</span><span>연고지</span></div><div className="club-select-list">{clubs.filter(v=>v.league===lid).map(v=><button key={v.id} className={`club-option ${v.id===cid?'selected':''}`} aria-pressed={v.id===cid} onClick={()=>setCid(v.id)}><Badge club={v} size="small"/><strong>{v.name}</strong><span className="club-city">{v.city}</span>{v.id===cid&&<Check size={14}/>}</button>)}</div><div className="database-note"><Shield size={15}/><span>실명·가상 선수 포함</span><button className="text-button" onClick={()=>setHelp(true)}>데이터 안내<ChevronRight size={13}/></button></div></section>
 <aside className="club-picker"><div className="chosen-club" style={{'--club':c.color} as CSSProperties}><Badge club={c} size="large"/><div><small>{l.name}</small><h2>{c.name}</h2><span>{c.city}</span></div></div><div className="club-facts"><div><span>운영 예산</span><strong>{money(teamBudget(lid))}</strong></div><div><span>선수단</span><strong>{roster.length}명</strong></div><div><span>실명 선수</span><strong>{roster.filter(p=>p.real).length}명</strong></div></div>
 <div className="key-players"><div className="selector-heading"><h2>주요 선수</h2><span>능력</span></div>{featured.map(p=><div className="setup-player" key={p.id}><span className="position-code">{p.pos}</span><span>{p.name}<small>{p.real?'실명':'가상'} · {p.ageEstimated?'게임 나이 ':''}{p.age}세</small></span><Rating value={overall(p)} player={p}/></div>)}</div>
 <div className="career-fields"><label htmlFor="manager">감독 이름<input id="manager" maxLength={24} value={manager} onChange={e=>setManager(e.target.value)}/></label><label>시즌 길이<Choice value={mode} onChange={setMode} label="시즌 길이" items={[{value:'short',label:'단축 · 상대별 2경기 / 2연전'},{value:'full',label:`정규 길이 · 약 ${l.games}경기`}]}/></label></div>
 <div className="preseason-settings"><strong>프리시즌부터 시작 · 4주</strong><p>연습경기 4회 · 전술 훈련 · 선수단 정비</p><label><input type="checkbox" checked={ban} onChange={e=>setBan(e.target.checked)}/>첫 시즌 외부 선수 영입 금지</label><small>FA 포함 · 재계약, 매각, 코치 선임 가능</small><label><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/>잠재력 공개</label><small>기본은 숨김 · 이 커리어를 시작한 뒤에는 변경할 수 없습니다.</small></div><button className="button primary start-button" disabled={busy||loading||!!error} onClick={()=>onStart(cid,manager,mode,ban,reveal)}>{busy||loading?<LoaderCircle size={16} className="spin"/>:<><span>{c.short} 감독으로 취임</span><ChevronRight size={18}/></>}</button><p className="tiny text-center">경기와 계약은 자동 저장됩니다.</p></aside></div>
 <div className="setup-bottom"><span>2026 시즌 · {clubs.length}개 구단</span><button className="text-button" onClick={()=>setHelp(true)}>게임 규칙</button></div></main><Help open={help} close={()=>setHelp(false)}/></div>;
}
function Dashboard({g,setView,simulate,act,busy,onPlayer,replay}:{g:GameState;setView:(v:string)=>void;simulate:()=>void;act:Act;busy:boolean;onPlayer:(p:Player)=>void;replay:(r:Result)=>void}){
 const {getClub,getLeague,standings,nextFixture}=useWorld();const rows=standings(g),own=rows.find(s=>s.club===g.club)!,rank=rows.findIndex(s=>s.club===g.club)+1,fixture=nextFixture(g);const players=g.lineup.map(id=>g.roster.find(p=>p.id===id)!);const pitcher=g.roster.find(p=>p.id===g.starter),top=[...g.roster].sort((a,b)=>overall(b)-overall(a)).slice(0,4);const [selectedNews,setSelectedNews]=useState<string|null>(null);const selected=g.news.find(n=>n.id===selectedNews)||g.news[0];
 return <><div className="metrics"><Metric label="리그 순위" value={<>{rank}<small> / {rows.length}</small></>} sub={`${own.w}승 ${own.l}패 ${own.d}무 · ${(own.w/(own.w+own.l||1)).toFixed(3)}`}/><Metric label="운영 예산" value={money(g.budget)} sub={g.budget<0?'예산 적자':'영입 · 계약 · 운영'}/><Metric label="선수단 컨디션" value={<>{Math.round(g.roster.reduce((s,p)=>s+p.condition,0)/g.roster.length)}<small>%</small></>} sub={`${g.roster.length}명 · ${g.staff.length}명의 코치`}/><Metric label="최근 경기" value={<div className="form">{own.form.length?own.form.map((v,i)=><span className={v} key={i}>{v}</span>):Array.from({length:5},(_,i)=><span key={i}>–</span>)}</div>} sub="최근 5경기"/></div>
 <div className="dashboard-grid"><aside className="briefing-column"><InboxPanel g={g} act={act} busy={busy} onPlayer={onPlayer} compact/>
 <section className="panel"><div className="panel-header"><h2>주요 선수</h2><button className="text-button" onClick={()=>setView('squad')}>선수단<ChevronRight size={12}/></button></div><div className="top-players">{top.map(p=><div key={p.id}><PlayerName p={p} onClick={onPlayer}/><Rating value={overall(p)} player={p}/></div>)}</div></section></aside>
 <div className="main-column"><section className="panel next-match"><div className="panel-header"><h2>다음 경기</h2><span>{g.phase==='preseason'?'프리시즌':g.phase==='regular'?'정규 시즌':g.phase==='finished'?'시즌 종료':'포스트시즌'}</span></div>{fixture?<><div className="match-meta"><span>{getLeague(getClub(g.club).league).name}</span><span>{dateLabel(g)} · {getClub(fixture[0]).city}</span></div><div className="matchup"><div><Badge club={getClub(fixture[1])} size="large"/><strong>{getClub(fixture[1]).name}</strong><small>원정</small></div><div className="versus"><b>v</b></div><div><Badge club={getClub(fixture[0])} size="large"/><strong>{getClub(fixture[0]).name}</strong><small>홈</small></div></div><div className="match-bottom"><span>선발 <strong>{pitcher?.name}</strong><span className="muted">{Math.round(pitcher?.condition||0)}%</span></span><button className="text-button" disabled={busy} onClick={simulate}>경기 진행<ChevronRight size={14}/></button></div></>:<div className="empty-state"><Trophy size={25}/><h3>{g.phase==='finished'?`${getClub(g.champion).name} 우승`:'예정된 경기가 없습니다'}</h3><p>{g.phase==='finished'?'재계약을 확인한 뒤 다음 시즌을 시작하세요.':'선수단을 정비하거나 다음 날로 진행하세요.'}</p></div>}</section>
 <section className="panel"><div className="panel-header"><h2>전술 · 수비 배치</h2><button className="text-button" onClick={()=>setView('tactics')}>설정<ChevronRight size={13}/></button></div><DefensiveField g={g} onPlayer={onPlayer} compact/><div className="tactic-summary"><Target size={14}/><strong>{tactics.find(t=>t[0]===g.tactic)?.[1]}</strong><span>선발 {players.length}명</span></div></section></div>
 <aside className="right-column"><section className="panel"><div className="panel-header"><h2>리그 순위</h2><button className="text-button" onClick={()=>setView('world')}>전체<ChevronRight size={13}/></button></div><StandingsTable g={g} compact/></section><section className="panel"><div className="panel-header"><h2>최근 결과</h2><button className="text-button" onClick={()=>setView('schedule')}>일정<ChevronRight size={13}/></button></div>{g.history.length?<div className="compact-results">{g.history.slice(0,5).map(r=><button key={r.id} onClick={()=>replay(r)}><small>{r.date?.slice(5).replace('-','/')||dateLabel(g,r.day)}</small><span>{getClub(r.away).short}</span><strong>{r.awayScore}–{r.homeScore}</strong><span>{getClub(r.home).short}</span><ChevronRight size={12}/></button>)}</div>:<div className="empty-state"><p>아직 치른 경기가 없습니다.</p></div>}</section><section className="panel club-checklist"><div className="panel-header"><h2>계약 현황</h2></div><button onClick={()=>setView('agents')}><span>진행 중인 협상</span><b>{g.deals.length}</b><ChevronRight size={13}/></button><button onClick={()=>setView('squad')}><span>계약 잔여 1년</span><b>{g.roster.filter(p=>p.years===1).length}명</b><ChevronRight size={13}/></button><button onClick={()=>setView('staff')}><span>코칭 스태프</span><b>{g.staff.length}명</b><ChevronRight size={13}/></button></section></aside></div></>;
}
function StandingsTable({g,league,compact=false}:{g:GameState;league?:string;compact?:boolean}){const {getClub,standings}=useWorld();const rows=standings(g,league);const ownIndex=rows.findIndex(s=>s.club===g.club);const show=compact?(ownIndex>=8?[...rows.slice(0,7),rows[ownIndex]]:rows.slice(0,8)):rows;return <Table className="data-table standings-table"><TableHeader><TableRow><TableHead>#</TableHead><TableHead>구단</TableHead><TableHead>승</TableHead><TableHead>패</TableHead>{!compact&&<TableHead>무</TableHead>}<TableHead>승률</TableHead>{!compact&&<><TableHead>승차</TableHead><TableHead>득실</TableHead><TableHead>최근 5경기</TableHead></>}</TableRow></TableHeader><TableBody>{show.map((s,i)=><TableRow key={s.club} className={s.club===g.club?'my-team':''}><TableCell>{rows.indexOf(s)+1}</TableCell><TableCell><span className="table-club"><Badge club={getClub(s.club)} size="tiny"/>{compact?getClub(s.club).short:getClub(s.club).name}{s.club===g.club&&<span className="you">MY</span>}</span></TableCell><TableCell>{s.w}</TableCell><TableCell>{s.l}</TableCell>{!compact&&<TableCell>{s.d}</TableCell>}<TableCell>{s.w+s.l?(s.w/(s.w+s.l)).toFixed(3):'.000'}</TableCell>{!compact&&<><TableCell>{i===0?'–':((rows[0].w-s.w+s.l-rows[0].l)/2).toFixed(1)}</TableCell><TableCell>{s.rf-s.ra>0?'+':''}{s.rf-s.ra}</TableCell><TableCell><span className="form">{s.form.map((v,j)=><span key={j} className={v}>{v}</span>)}</span></TableCell></>}</TableRow>)}</TableBody></Table>}
function PlayerTable({players,onPlayer,kind='squad',g}:{players:Player[];onPlayer:(p:Player)=>void;kind?:string;g:GameState}){const {getClub}=useWorld();return <Table className="data-table player-table"><TableHeader><TableRow><TableHead>선수</TableHead><TableHead>구분</TableHead><TableHead>나이</TableHead><TableHead>OVR</TableHead>{g.rules?.revealPotential&&<TableHead>잠재력</TableHead>}{kind==='market'?<><TableHead>소속 구단</TableHead><TableHead>예상 이적료</TableHead><TableHead>연봉</TableHead></>:<><TableHead>사기</TableHead><TableHead>컨디션</TableHead><TableHead>경기</TableHead><TableHead>AVG / ERA</TableHead><TableHead>HR / 승</TableHead><TableHead>연봉</TableHead></>}<TableHead/></TableRow></TableHeader><TableBody>{players.map(p=><TableRow key={p.id}><TableCell><PlayerName p={p} onClick={onPlayer}/></TableCell><TableCell>{positions[p.pos]}{kind!=='market'&&<small className="block muted">{p.squad==='reserve'?'2군':'1군'}</small>}</TableCell><TableCell>{p.age}{p.ageEstimated&&<small className="block muted">게임 나이</small>}</TableCell><TableCell><Rating value={overall(p)} player={p}/></TableCell>{g.rules?.revealPotential&&<TableCell><span className="potential">{potentialText(p)}</span></TableCell>}{kind==='market'?<><TableCell><span className="muted">{p.club==='fa'?'FA · 자유계약':getClub(p.club)?.name||'이적 선수'}</span></TableCell><TableCell>{money(askPrice(p))}</TableCell><TableCell>{money(p.salary)}</TableCell></>:<><TableCell><Mood p={p}/></TableCell><TableCell><div className="condition"><Progress value={p.condition}/><span>{Math.round(p.condition)}%</span></div></TableCell><TableCell>{p.stats.g}</TableCell><TableCell>{p.pos==='P'?p.stats.outs?(p.stats.er*27/p.stats.outs).toFixed(2):'–':p.stats.ab?(p.stats.h/p.stats.ab).toFixed(3):'–'}</TableCell><TableCell>{p.pos==='P'?p.stats.wins:p.stats.hr}</TableCell><TableCell>{money(p.salary)}<small className="block muted">{p.years}년 남음</small></TableCell></>}<TableCell><button className="icon-button" aria-label={`${p.name} 상세 보기`} onClick={()=>onPlayer(p)}><ArrowUpRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>}
function Squad({g,onPlayer}:{g:GameState;onPlayer:(p:Player)=>void}){const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[sort,setSort]=useState('rating');const list=g.roster.filter(p=>(filter==='all'||p.pos===filter||filter==='young'&&p.age<=23)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='age'?a.age-b.age:sort==='salary'?b.salary-a.salary:overall(b)-overall(a));return <section className="panel"><div className="toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList variant="line">{[['all','전체 선수'],['P','투수'],['C','포수'],['IF','내야수'],['OF','외야수'],['young','유망주']].map(t=><TabsTrigger value={t[0]} key={t[0]}>{t[1]}</TabsTrigger>)}</TabsList></Tabs><div className="toolbar-controls"><SearchBox value={query} onChange={setQuery}/><Choice label="선수 정렬" value={sort} onChange={setSort} items={[{value:'rating',label:'능력치 순'},{value:'age',label:'어린 선수 순'},{value:'salary',label:'연봉 순'}]}/></div></div><PlayerTable players={list} onPlayer={onPlayer} g={g}/>{!list.length&&<Empty text="조건에 맞는 선수가 없습니다."/>}<div className="panel-foot">{list.length}명 · 실명 {list.filter(p=>p.real).length}명 / 가상 {list.filter(p=>!p.real).length}명<span>OVR: 2025 공식 성적 기반 · * 적은 표본 · 잠재력은 추정</span></div></section>}
function SearchBox({value,onChange,placeholder='선수 검색'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="search-box"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="검색어 지우기" onClick={()=>onChange('')}><X size={14}/></button>}</label>}
function Empty({text}:{text:string}){return <div className="empty-state"><Search size={27}/><p>{text}</p></div>}
function World({g,onPlayer}:{g:GameState;onPlayer:(p:Player)=>void}){const {clubs,leagues,getClub,getLeague,rosterFor}=useWorld();const [lid,setLid]=useState(getClub(g.club).league),[team,setTeam]=useState('');const l=getLeague(lid);const roster=team&&team!=='none'?rosterFor(g,team):[];return <><div className="world-strip">{leagues.map(v=><button key={v.id} className={lid===v.id?'selected':''} onClick={()=>{setLid(v.id);setTeam('')}}><span>{v.flag}</span><strong>{v.name}</strong><small>{v.country}</small></button>)}</div><section className="panel"><div className="panel-header"><h2>{l.flag} {l.label}</h2><a href={l.source} target="_blank" rel="noreferrer" className="text-button">공식 리그 <ExternalLink size={14}/></a></div><StandingsTable g={g} league={lid}/><div className="panel-foot">{l.country} · {l.season}<span>게임 내 순위 · 현실 리그 성적과 별도</span></div></section><section className="panel club-inspector"><div className="panel-header"><h2>세계 구단 선수단</h2><Choice label="구단 선수단 보기" value={team||'none'} onChange={setTeam} items={[{value:'none',label:'구단을 선택하세요'},...clubs.filter(c=>c.league===lid).map(c=>({value:c.id,label:c.name}))]}/></div>{team&&team!=='none'?<PlayerTable players={[...roster].sort((a,b)=>overall(b)-overall(a))} onPlayer={onPlayer} kind="market" g={g}/>:<Empty text="구단을 선택하면 실명 선수와 유망주를 살펴볼 수 있습니다."/>}</section></>}
function Market({g,onPlayer}:{g:GameState;onPlayer:(p:Player)=>void}){const {leagues,getClub,marketPlayers}=useWorld();const [query,setQuery]=useState(''),[lid,setLid]=useState('all'),[pos,setPos]=useState('all'),[kind,setKind]=useState('all'),[page,setPage]=useState(0),[sort,setSort]=useState('rating');const market=useMemo(()=>marketPlayers(g),[g,marketPlayers]);const list=useMemo(()=>market.filter(p=>(lid==='all'||lid==='fa'&&p.club==='fa'||getClub(p.club)?.league===lid)&&(pos==='all'||p.pos===pos)&&(kind==='all'||kind==='real'&&p.real||kind==='generated'&&!p.real)&&`${p.name} ${p.original}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='value'?askPrice(a)-askPrice(b):sort==='potential'&&g.rules?.revealPotential?b.potential-a.potential:overall(b)-overall(a)),[market,lid,pos,kind,query,sort,g.rules?.revealPotential,getClub]);const pages=Math.max(1,Math.ceil(list.length/25));const current=Math.min(page,pages-1);return <>{transfersBlocked(g)&&<div className="rule-notice">첫 시즌 영입 금지 · {g.rules!.startYear+1}년부터 외부 선수와 FA를 영입할 수 있습니다.</div>}<div className="market-notice"><Globe2 size={24}/><div><strong>선수 검색 · 영입 현황</strong><p>{market.filter(p=>p.real).length.toLocaleString()}명의 실명 선수와 {market.filter(p=>!p.real).length.toLocaleString()}명의 가상 선수 · 스카우트 능력 {coachSkill(g,'스카우트')}</p></div><div><span className="label">사용 가능한 예산</span><strong className="accent">{money(g.budget)}</strong></div></div><section className="panel"><div className="market-filters"><SearchBox value={query} onChange={s=>{setQuery(s);setPage(0)}} placeholder="선수 이름 검색 · 오타니, 저지, 김도영"/><Choice label="리그 필터" value={lid} onChange={v=>{setLid(v);setPage(0)}} items={[{value:'all',label:'전 세계 리그'},{value:'fa',label:'FA · 자유계약'},...leagues.map(l=>({value:l.id,label:`${l.flag} ${l.name}`}))]}/><Choice label="포지션 필터" value={pos} onChange={v=>{setPos(v);setPage(0)}} items={[{value:'all',label:'모든 포지션'},...Object.entries(positions).map(([value,label])=>({value,label}))]}/><Choice label="선수 유형" value={kind} onChange={v=>{setKind(v);setPage(0)}} items={[{value:'all',label:'실명 + 가상'},{value:'real',label:'실명 선수'},{value:'generated',label:'가상 선수'}]}/><Choice label="시장 정렬" value={sort} onChange={setSort} items={[{value:'rating',label:'능력치 높은 순'},...(g.rules?.revealPotential?[{value:'potential',label:'잠재력 높은 순'}]:[]),{value:'value',label:'이적료 낮은 순'}]}/></div><PlayerTable players={list.slice(current*25,(current+1)*25)} g={g} onPlayer={onPlayer} kind="market"/>{!list.length&&<Empty text="검색 조건에 맞는 선수가 없습니다."/>}<div className="pagination"><span>{list.length.toLocaleString()}명 중 {list.length?current*25+1:0}–{Math.min((current+1)*25,list.length)}</span><div><button aria-label="이전 페이지" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button><span>{current+1} / {pages}</span><button aria-label="다음 페이지" disabled={current>=pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={18}/></button></div></div></section></>}
function Agents({g,act,busy,onPlayer}:{g:GameState;act:Act;busy:boolean;onPlayer:(p:Player)=>void}){const {agentFor}=useWorld();return <><div className="agent-intro"><Handshake size={28}/><div><h3>계약 테이블</h3><p>수락된 조건이나 역제안에 최종 서명하면 이적료·계약금·수수료가 지출됩니다. 제안은 14일간 유효합니다.</p></div></div>{g.deals.length?<div className="deal-grid">{g.deals.map(d=>{const a=agentFor(d.player);return <section className="panel deal-card" key={d.id}><div className="panel-header"><span className={`pill ${d.status==='accepted'?'lime':d.status==='counter'?'amber':''}`}>{d.status==='accepted'?'계약 합의':d.status==='counter'?'역제안 도착':'제안 거절'}</span><span className="muted">{d.type==='renew'?'재계약':'신규 영입'}</span></div><div className="panel-content"><div className="deal-player"><PlayerName p={d.player} onClick={onPlayer}/><Rating value={overall(d.player)} player={d.player}/></div><p className="agent-message">“{d.message}”</p>{d.seller&&<p className="tiny"><strong>소속 구단 · {d.seller.role}</strong><br/>{d.seller.reason}</p>}<div className="agent-signature"><span className="manager-avatar"><UserRound size={19}/></span><span><strong>{a.name}</strong><small>{a.agency} · 수수료 {(a.fee*100).toFixed(0)}%</small></span></div><div className="deal-terms"><div><small>연봉</small><strong>{money(d.salary)}</strong></div><div><small>계약 기간</small><strong>{d.years}년</strong></div><div><small>이적료</small><strong>{money(d.fee)}</strong></div></div><div className="cost-line"><span>지금 지출 · 계약금 15% + 수수료 + 이적료</span><strong>{money(d.fee+d.agentFee+d.salary*.15)}</strong></div><button className="button primary full-width" disabled={busy||d.status==='rejected'||g.day-d.day>14||(d.type==='buy'&&transfersBlocked(g))} onClick={async()=>{if(await act({type:'sign',id:d.id}))toast.success('계약에 서명했습니다. 선수단에서 확인하세요.')}}>{g.day-d.day>14?'제안 만료':d.status==='counter'?'역제안 수락 · 계약 체결':'최종 서명'}<Check size={16}/></button></div></section>})}</div>:<section className="panel"><div className="empty-state"><Handshake size={42}/><h3>진행 중인 협상이 없습니다</h3><p>영입 · 이적에서 선수를 선택해 에이전트에게 제안하세요.<br/>소속 선수의 상세 화면에서는 재계약을 제안할 수 있습니다.</p></div></section>}</>}
function Finance({g,ledger}:{g:GameState;ledger:FinanceEntry[]}){const wages=g.roster.reduce((s,p)=>s+p.salary,0),coaches=g.staff.reduce((s,c)=>s+c.salary,0);return <><div className="metrics"><Metric label="현재 잔액" value={money(g.budget)} sub="영입 및 운영 예산" icon={<Wallet size={18}/>}/><Metric label="이번 시즌 수입" value={money(g.income)} sub="경기 수익 · 매각 · 상금" icon={<ArrowUpRight size={18}/>}/><Metric label="이번 시즌 지출" value={money(g.expenses)} sub="급여 · 계약금 · 이적료 · 수수료" icon={<Banknote size={18}/>}/><Metric label="총 연간 급여" value={money(wages+coaches)} sub="선수와 코치의 연봉 합계" icon={<Users size={18}/>}/></div><section className="panel ledger-panel"><div className="panel-header"><h2>거래 내역</h2><span>최근 60건 · 자동 기록</span></div><Table><TableHeader><TableRow><TableHead>시즌 · 일차</TableHead><TableHead>내용</TableHead><TableHead>변동</TableHead><TableHead>잔액</TableHead></TableRow></TableHeader><TableBody>{ledger.map(e=><TableRow key={e.id}><TableCell>{e.year} · {dateLabel(g,e.day)}</TableCell><TableCell>{{start:'구단 운영 자금',advance:'경기 수입 · 급여',continue:'날짜 진행 · 경기 수입 · 급여',sign:'선수 계약',sell:'선수 매각',coach:'코치 계약',nextSeason:'새 시즌 지원금'}[e.kind]||e.kind}</TableCell><TableCell className={e.amount>0?'accent':''}>{e.amount>0?'+':'−'}{money(Math.abs(e.amount))}</TableCell><TableCell>{money(e.balance)}</TableCell></TableRow>)}</TableBody></Table>{!ledger.length&&<Empty text="아직 거래 내역이 없습니다."/>}</section><div className="two-column"><section className="panel"><div className="panel-header"><h2>연봉 상위 선수</h2><span>게임 내 계약</span></div><div className="salary-list">{[...g.roster].sort((a,b)=>b.salary-a.salary).slice(0,10).map(p=><div key={p.id}><strong>{p.name}</strong><span className="muted">{p.years}년</span><div><Progress value={p.salary/Math.max(...g.roster.map(p=>p.salary))*100}/></div><b>{money(p.salary)}</b></div>)}</div></section><div><section className="panel"><div className="panel-header"><h2>운영 구조</h2></div><div className="panel-content finance-details"><div><span>선수 연봉 합계</span><strong>{money(wages)}</strong></div><div><span>코치 연봉 합계</span><strong>{money(coaches)}</strong></div><div><span>하루 급여 지출</span><strong>{money((wages+coaches)/(g.rounds+(g.rules?.preseason?28:0)))}</strong></div><p>금액은 원화로 표시하며 계약 연봉은 만 원 단위로 입력합니다. 게임 고정 환산 기준은 1달러 = 1,400원이며, 실제 환율·선수 연봉과는 다릅니다.</p><p>홈 경기는 원정 경기보다 수입이 높고, 승리하면 보너스 수입이 발생합니다. 새 시즌에는 구단 지원금이 지급됩니다.</p></div></section><section className="panel training-block"><div className="panel-header"><h2>커리어 기록</h2><Trophy size={18}/></div>{g.past.length?<div className="panel-content">{g.past.map(y=><div className="career-record" key={y.year}><strong>{y.year}</strong><span>{y.rank}위 · {y.w}승 {y.l}패</span>{y.champion===g.club&&<span className="pill lime">우승</span>}</div>)}</div>:<Empty text="첫 시즌을 마치면 커리어 기록이 남습니다."/>}</section></div></div></>}
function Help({open,close}:{open:boolean;close:()=>void}){const {rosterNote}=useWorld();return <Dialog open={open} onOpenChange={o=>{if(!o)close()}}><DialogContent className="game-dialog help-dialog"><DialogHeader><DialogTitle>DUGOUT 플레이 가이드</DialogTitle><DialogDescription>구단 선택부터 챔피언십까지</DialogDescription></DialogHeader><div className="help-copy"><h3>프리시즌 · 전술</h3><p>새 커리어는 개막 4주 전 시작합니다. 주 1회 연습경기는 정규 성적에 포함되지 않습니다. 전술 화면에서 수비 선수를 드래그하거나 클릭해 배치하고, 팀 지시와 타순을 이름 붙여 저장할 수 있습니다. 포지션 숙련도는 수비력에 영향을 줍니다. 첫 시즌 영입 금지 옵션은 FA를 포함하며, 다음 해에 해제됩니다.</p><h3>시즌 진행</h3><p>타순과 선발, 공격 전술을 정한 뒤 경기를 진행하세요. 선수 능력과 컨디션, 코칭이 경기와 성장에 반영됩니다. 경기 결과는 리플레이에서 이닝별로 확인할 수 있습니다.</p><h3>영입 · 이적 · 에이전트</h3><p>시장에서 선수를 선택해 계약을 제안하고, 에이전트 메뉴에서 합의나 역제안에 서명하세요. 소속 구단이 주전 역할·대체 전력·잔여 계약·순위 경쟁을 검토해 이적을 거절하거나 높은 이적료를 요구할 수 있습니다. 내 선수는 이적 명단에 올린 뒤 실제로 도착한 구단 제안만 수락할 수 있습니다. 단축 시즌의 구단 간 이적은 시즌 80%에서 마감됩니다. 다음 시즌 전 계약 잔여 1년인 선수를 확인하세요.</p><h3>수신함 · 선수단 분위기</h3><p>경기 날짜에 맞춰 시리즈 분석, 훈련과 계약 보고가 도착합니다. 출전 부족·경기 결과·약속 이행이 선수 사기에 반영되며, 면담이 새로 생기면 여러 날 진행이 멈춥니다. 수신함에서 답변하거나 선수단 분위기에서 원인을 확인하세요. 선수의 감정과 발언은 게임 내 가상 상태입니다.</p><h3>코치 · 가상 신인</h3><p>KBO 실명 코치와 가상 코치를 5개 분야에 선임할 수 있습니다. 2군에서 별도 경기와 훈련을 통해 선수를 육성하고 1군으로 올릴 수 있습니다. 시즌을 넘기면 나이와 계약 기간이 변하고 가상 신인이 입단합니다. 실명 선수와 가상 선수는 배지로 구분합니다.</p><h3>리그와 게임 규칙</h3><p>13개 리그의 구단으로 플레이할 수 있습니다. 2026 MLB·NPB는 공식 날짜와 대진을 사용합니다. KBO는 최초 편성 675경기와 공식 잔여 대진 45경기를 조합한 144경기 일정이며 우천 취소는 재현하지 않습니다. 그 외 리그·다음 시즌·단축 모드는 연전과 휴식일을 포함해 편성합니다. 단축 모드는 상대별 2경기입니다. 모든 리그에 통합 순위와 상위 4팀 플레이오프(준결승 3전 2선승, 결승 5전 3선승)를 적용합니다. 실제 지구별 진출·전후기·포스팅·외국인 제한·국가별 2군 운영·국제대회 규정은 아직 적용하지 않았습니다.</p><h3>선수 데이터</h3><p>{rosterNote} MLB·NPB는 공개 등록 명단, KBO는 10개 구단의 9월 7일 1군 등록 명단과 기존 실명 명단을 반영했으며, 전체 소속 선수 명단과 차이가 있을 수 있습니다. 기타 리그는 일부 실명 선수를 반영했습니다. 겨울 리그는 2025–26 구성 기준입니다. 정보 확인일: 2026-09-07.</p><p>에이전트는 가상 인물입니다. 실명 코치의 이름과 등록 소속은 공식 명단 기준이며 능력·연봉·게임 담당 보직은 게임 설정입니다. 실제 인물이나 소속사의 계약 조건을 재현하지 않습니다. 선수 이적은 국가별 법적 절차를 생략한 게임 규칙으로 처리합니다.</p><div className="source-links"><a href="https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx" target="_blank" rel="noreferrer">KBO 선수 기록 ↗</a><a href="https://www.mlb.com/dodgers/roster" target="_blank" rel="noreferrer">MLB 공개 로스터 ↗</a><a href="https://npb.jp/bis/eng/teams/rst_g.html" target="_blank" rel="noreferrer">NPB 등록 명단 ↗</a></div></div></DialogContent></Dialog>}

type CareerData={state:GameState|null;revision:number;ledger:FinanceEntry[]};
export default function Game({initialPlayerId,initialView}:{initialPlayerId?:string;initialView?:string}={}){
 const [data,setData]=useState<{world:WorldCatalog;career:CareerData}|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const abort=new AbortController();setError('');Promise.all(['/api/catalog','/api/career'].map(async url=>{const response=await fetch(url,{cache:'no-store',signal:abort.signal});const body=await response.json();if(!response.ok)throw new Error(body.error||'데이터를 불러오지 못했습니다.');return body;})).then(([world,career])=>setData({world,career})).catch(e=>{if(!abort.signal.aborted)setError(e.message||'연결하지 못했습니다.');});return()=>abort.abort();},[attempt]);
 if(!data)return <main className="catalog-loading"><div className="brand"><Baseball/><span>DUGOUT<i>WORLD BASEBALL MANAGER</i></span></div>{error?<><h1>커리어를 불러오지 못했습니다</h1><p>{error}</p><button className="button primary" onClick={()=>setAttempt(n=>n+1)}>다시 연결</button></>:<><LoaderCircle size={32} className="spin"/><h1>커리어 불러오는 중</h1><p>리그, 선수단, 저장된 커리어를 불러오는 중입니다.</p></>}</main>;
 return <WorldProvider world={data.world}><GameScreen initial={data.career} initialPlayerId={initialPlayerId} initialView={initialView} refreshCatalog={async()=>{const response=await fetch('/api/catalog',{cache:'no-store'});if(!response.ok)throw new Error('선수 DB를 새로 불러오지 못했습니다. 새로고침해 주세요.');const world=await response.json();setData(current=>current?{...current,world}:current)}}/></WorldProvider>;
}
