import { env } from 'cloudflare:workers';
import { headers } from 'next/headers';
import { applyAction, newGame, type GameState } from '@/lib/engine';
export const dynamic='force-dynamic';
async function identity(){return (await headers()).get('oai-authenticated-user-id');}
function db(){if(!env.DB)throw new Error('저장 서비스에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.');return env.DB;}
const options={headers:{'Cache-Control':'no-store'}};
export async function GET(){const user=await identity();if(!user)return Response.json({error:'커리어를 불러오려면 로그인해 주세요.'},{status:401,...options});try{const row=await db().prepare('SELECT state, revision FROM careers WHERE user_id = ?').bind(user).first<{state:string;revision:number}>();return Response.json({state:row?JSON.parse(row.state):null,revision:row?.revision||0},options);}catch(e){console.error('career read',e);return Response.json({error:'저장된 커리어를 불러오지 못했습니다. 다시 시도해 주세요.'},{status:503,...options});}}
export async function POST(request:Request){const user=await identity();if(!user)return Response.json({error:'로그인 후 다시 시도해 주세요.'},{status:401,...options});const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'요청 출처를 확인할 수 없습니다.'},{status:403,...options});let action:Record<string,unknown>;try{const raw=await request.text();if(raw.length>12000)return Response.json({error:'요청이 너무 큽니다.'},{status:413});action=JSON.parse(raw);if(!action||typeof action!=='object')throw new Error();}catch{return Response.json({error:'요청 형식이 올바르지 않습니다.'},{status:400,...options});}
 try{const row=await db().prepare('SELECT state, revision FROM careers WHERE user_id = ?').bind(user).first<{state:string;revision:number}>();const expected=Number(action.revision);if(!Number.isInteger(expected)||expected!==(row?.revision||0))return Response.json({error:'다른 화면에서 커리어가 변경됐습니다. 최신 상태를 불러왔습니다.',state:row?JSON.parse(row.state):null,revision:row?.revision||0},{status:409,...options});let state:GameState;
 try{if(action.type==='start'){if(row&&!action.replace)throw new Error('기존 커리어 교체를 확인해 주세요.');if(!['short','full'].includes(String(action.mode)))throw new Error('시즌 길이를 선택해 주세요.');state=newGame(String(action.club),String(action.manager||'감독'),action.mode as 'short'|'full');}else{if(!row)throw new Error('먼저 커리어를 시작해 주세요.');state=applyAction(JSON.parse(row.state),action);}}catch(e){return Response.json({error:e instanceof Error?e.message:'요청을 처리하지 못했습니다.'},{status:400,...options});}
 const serialized=JSON.stringify(state);if(serialized.length>1500000)throw new Error('Career data too large');const now=new Date().toISOString();let changes=0;
 if(row){const result=await db().prepare('UPDATE careers SET state = ?, revision = revision + 1, updated_at = ? WHERE user_id = ? AND revision = ?').bind(serialized,now,user,expected).run();changes=result.meta.changes;}else{const result=await db().prepare('INSERT INTO careers (user_id, state, revision, updated_at) VALUES (?, ?, 1, ?) ON CONFLICT(user_id) DO NOTHING').bind(user,serialized,now).run();changes=result.meta.changes;}
 if(!changes)return Response.json({error:'다른 요청이 먼저 저장됐습니다. 최신 커리어를 다시 불러와 주세요.'},{status:409,...options});return Response.json({state,revision:expected+1},options);
 }catch(e){console.error('career write',e);return Response.json({error:'변경을 저장하지 못했습니다. 현재 화면을 유지했습니다. 다시 시도해 주세요.'},{status:503,...options});}}
