import { clubs, leagues, getClub, getLeague, realRosters, type RealSeed } from './catalog';
export type Pos='P'|'C'|'IF'|'OF'|'DH';
export type Stats={ab:number;h:number;hr:number;rbi:number;bb:number;k:number;outs:number;er:number;wins:number;g:number};
export type Player={id:string;name:string;original:string;club:string;pos:Pos;age:number;real:boolean;country:string;number:number;contact:number;power:number;speed:number;field:number;stuff:number;control:number;potential:number;condition:number;salary:number;years:number;stats:Stats;source?:string};
export type Coach={id:string;name:string;role:string;skill:number;salary:number;style:string};
export type Standing={club:string;w:number;l:number;d:number;rf:number;ra:number;form:string[]};
export type Result={id:string;day:number;home:string;away:string;homeScore:number;awayScore:number;innings:(number|null)[][];hits:number[];errors:number[];log:{inning:number;half:number;text:string;score:number[]}[];mvp:string;post?:boolean};
export type Deal={id:string;player:Player;type:'buy'|'renew';salary:number;years:number;fee:number;agentFee:number;status:'accepted'|'counter'|'rejected';message:string;day:number};
export type GameState={version:1;year:number;day:number;club:string;manager:string;budget:number;seed:number;rounds:number;mode:'short'|'full';roster:Player[];lineup:string[];starter:string;tactic:string;training:string;staff:Coach[];standings:Record<string,Standing[]>;history:Result[];news:{id:string;day:number;title:string;body:string;kind:string}[];deals:Deal[];ownership:Record<string,string>;transferred:Player[];past:{year:number;rank:number;w:number;l:number;champion:string}[];phase:'regular'|'semifinal'|'final'|'finished';series:{a:string;b:string;aw:number;bw:number}[];champion:string;reputation:number;income:number;expenses:number};
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export const blankStats=():Stats=>({ab:0,h:0,hr:0,rbi:0,bb:0,k:0,outs:0,er:0,wins:0,g:0});
export function hash(s:string){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
export function rng(seed:number){let a=seed;return ()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
const aliases:Record<string,string>={'Shohei Ohtani':'오타니 쇼헤이','Aaron Judge':'애런 저지','Mookie Betts':'무키 베츠','Freddie Freeman':'프레디 프리먼','Yoshinobu Yamamoto':'야마모토 요시노부','Roki Sasaki':'사사키 로키','Jung Hoo Lee':'이정후','Ha-Seong Kim':'김하성','Hyeseong Kim':'김혜성','Juan Soto':'후안 소토','Bobby Witt Jr.':'바비 위트 주니어','Paul Skenes':'폴 스킨스','Tarik Skubal':'타릭 스쿠벌','Shota Imanaga':'이마나가 쇼타','Seiya Suzuki':'스즈키 세이야','Yusei Kikuchi':'기쿠치 유세이','Munetaka Murakami':'무라카미 무네타카','Kazuma Okamoto':'오카모토 가즈마','Teruaki Sato':'사토 데루아키','Koji Chikamoto':'지카모토 고지','Shota Morishita':'모리시타 쇼타','Shosei Togo':'도고 쇼세이','Hayato Sakamoto':'사카모토 하야토','Yuki Yanagita':'야나기타 유키','Kensuke Kondoh':'곤도 겐스케','Chusei Mannami':'만나미 주세이','Hiromi Itoh':'이토 히로미','Hiroto Saiki':'사이키 히로토'};
const stars:Record<string,number>={'Shohei Ohtani':98,'Aaron Judge':98,'Juan Soto':96,'Bobby Witt Jr.':96,'Paul Skenes':96,'Tarik Skubal':96,'Yoshinobu Yamamoto':93,'Mookie Betts':92,'Freddie Freeman':91,'Kyle Tucker':93,'Ronald Acuña Jr.':94,'José Ramírez':94,'Gunnar Henderson':92,'Cal Raleigh':92,'Julio Rodríguez':90,'Jung Hoo Lee':83,'Ha-Seong Kim':82,'Hyeseong Kim':79,'Seiya Suzuki':88,'Shota Imanaga':89,'Teruaki Sato':89,'Koji Chikamoto':87,'Shota Morishita':86,'Hiroto Saiki':88,'Shosei Togo':86,'Kensuke Kondoh':90,'김도영':92,'구자욱':89,'류현진':87,'문동주':85,'안우진':90,'김혜성':83,'강백호':88,'노시환':87,'양의지':87,'박동원':85,'최정':88,'김광현':84,'박세웅':83,'박민우':86,'오스틴':90,'나성범':86};
export function overall(p:Player){return Math.round(p.pos==='P'?p.stuff*.58+p.control*.42:p.contact*.40+p.power*.30+p.speed*.12+p.field*.18);}
export function money(n:number){return n>=100?`$${(n/100).toFixed(2)}M`:`$${Math.round(n*10)}K`;}
export function teamBudget(league:string){return league==='mlb'?18000:league==='npb'?6000:league==='kbo'?3500:['cpbl','lmb','lidom'].includes(league)?1600:800;}
const families=['김','이','박','최','정','강','윤','장','한','임','서','신'];const firsts=['지훈','민재','도현','준서','우진','태윤','시우','현준','도윤','승현','건우','민준','주원','은호','재민','동현'];
function generatedName(country:string,r:()=>number){const pick=(a:string[])=>a[Math.floor(r()*a.length)];if(country==='대한민국')return pick(families)+pick(firsts);if(country==='일본')return pick(['사토','다나카','스즈키','야마모토','이노우에','와타나베'])+' '+pick(['하루토','렌','유토','다이키','쇼타','타쿠미']);if(country==='대만')return pick(['린','천','왕','장','우','류'])+' '+pick(['즈하오','위천','보위','웨이팅','쥔제','위쉬엔']);if(['도미니카공화국','멕시코','베네수엘라','푸에르토리코'].includes(country))return pick(['Luis','José','Carlos','Miguel','Rafael','Diego'])+' '+pick(['Pérez','García','Martínez','Rodríguez','Castro','López','Santos','Méndez']);return pick(['Alex','Lucas','Daniel','James','Noah','Liam','Marco','Tom'])+' '+pick(['Miller','Wilson','Novak','Rossi','de Vries','Taylor','Harris','Clark']);}
export function makePlayer(club:string,index:number,real?:RealSeed,year=2026):Player {const c=club==='fa'?null:getClub(club);const l=getLeague(c?.league||'kbo');const r=rng(hash(`${club}:${index}:${real?.name||year}`));const country=real?.country||l.country;const name=real?.name||generatedName(country,r);const pos=(real?.pos||(['C','IF','IF','IF','IF','OF','OF','OF','DH','P','P','P','P','P','P','P','C','IF','OF','P','P','IF','OF','P','P','IF'][index%26])) as Pos;const base=real?(real.rating||stars[name]||Math.round(l.level-12+r()*22)):Math.round(l.level-23+r()*23);const att=()=>Math.round(clamp(base+(r()-.5)*18,28,99));const age=real?real.age+year-2026:18+Math.floor(r()*7);const p:Player={id:real?'real-'+hash(real.name):`${club}-gen-${year}-${index}`,name:aliases[name]||name,original:name,club,pos,age,real:!!real,country,number:real?.number??Math.floor(r()*98)+1,contact:att(),power:att(),speed:att(),field:att(),stuff:pos==='P'?att():Math.round(22+r()*25),control:pos==='P'?att():Math.round(25+r()*20),potential:clamp(base+(age<25?10+Math.floor(r()*15):Math.floor(r()*8)),base,99),condition:100,salary:0,years:1+Math.floor(r()*3),stats:blankStats(),source:real?.source};if(name==='Shohei Ohtani'){p.contact=96;p.power=99;p.speed=91;p.stuff=94;p.control=87;}p.salary=Math.max(5,Math.round(Math.pow(overall(p)/80,5)*(real?(l.id==='mlb'?650:145):22)));return p;}
const cache=new Map<string,Player[]>();
export function baseRoster(club:string,year=2026){const key=club+year;if(cache.has(key))return structuredClone(cache.get(key)!);const raw=realRosters[club]||[];let list=raw.map((p,i)=>makePlayer(club,i,p,year));const counts=(pos:Pos)=>list.filter(p=>p.pos===pos).length;
 for(const [pos,num] of [['P',10],['C',2],['IF',6],['OF',4],['DH',1]] as [Pos,number][]){while(counts(pos)<num){const p=makePlayer(club,100+list.length,undefined,year);p.pos=pos;if(pos==='P'){p.stuff=p.contact;p.control=p.field;}list.push(p);}}
 for(let i=0;i<3;i++)list.push(makePlayer(club,200+i,undefined,year));cache.set(key,structuredClone(list));return list;}
export function lineupAuto(roster:Player[]){const sorted=[...roster].filter(p=>p.pos!=='P').sort((a,b)=>(overall(b)*b.condition)-(overall(a)*a.condition));const chosen:Player[]=[];for(const [pos,n] of [['C',1],['IF',4],['OF',3]] as [Pos,number][]){chosen.push(...sorted.filter(p=>p.pos===pos).slice(0,n));}for(const p of sorted)if(chosen.length<9&&!chosen.includes(p))chosen.push(p);return chosen.sort((a,b)=>b.contact+b.speed*.4-a.contact-a.speed*.4).map(p=>p.id);}
export const coachRoles=['타격','투수','수비','체력','스카우트'];
export function coachPool(year=2026):Coach[]{return coachRoles.flatMap((role,i)=>Array.from({length:4},(_,n)=>{const r=rng(hash(`coach:${year}:${i}:${n}`));return{id:`coach-${year}-${i}-${n}`,name:generatedName(n%2?'미국 · 캐나다':'대한민국',r),role,skill:58+n*10+Math.floor(r()*7),salary:12+n*n*12,style:['기본기','유망주 육성','실전 중심','데이터 분석'][n]};}));}
export function coachSkill(g:GameState,role:string){return g.staff.find(c=>c.role===role)?.skill||35;}
export function rosterFor(g:GameState,id:string){if(id===g.club)return g.roster;return [...baseRoster(id,g.year).filter(p=>!g.ownership[p.id]),...(g.transferred||[]).filter(p=>p.club===id)];}
export function marketPlayers(g:GameState){const list=clubs.filter(c=>c.id!==g.club).flatMap(c=>baseRoster(c.id,g.year).filter(p=>!g.ownership[p.id]||g.ownership[p.id]===c.id));const own=new Set(g.roster.map(p=>p.id));const seen=new Set<string>();const free=Array.from({length:35},(_,i)=>{const p=makePlayer('fa',i,undefined,g.year);p.age=19+i%16;p.contact+=i%10;p.power+=i%8;return p;});return [...(g.transferred||[]),...list,...free].filter(p=>{if(own.has(p.id)||seen.has(p.id))return false;seen.add(p.id);return true;});}
export function standings(g:GameState,league=getClub(g.club).league){return [...g.standings[league]].sort((a,b)=>((b.w/(b.w+b.l||1))-(a.w/(a.w+a.l||1)))||(b.w-a.w)||((b.rf-b.ra)-(a.rf-a.ra))||a.club.localeCompare(b.club));}
function news(g:GameState,title:string,body:string,kind='club'){g.news.unshift({id:`${g.year}-${g.day}-${g.news.length}-${hash(title)}`,day:g.day,title,body,kind});g.news=g.news.slice(0,70);}
export function newGame(club:string,manager:string,mode:'short'|'full',seed=Date.now()):GameState {if(!getClub(club))throw new Error('구단을 선택해 주세요.');const league=getClub(club).league;const roster=baseRoster(club);const n=clubs.filter(c=>c.league===league).length;const g:GameState={version:1,year:2026,day:0,club,manager:manager.trim().slice(0,24)||'강경원',budget:teamBudget(league),seed:seed>>>0,rounds:mode==='short'?(n%2?n:n-1)*2:Math.ceil(getLeague(league).games/(n%2?(n-1)/n:1)),mode,roster,lineup:lineupAuto(roster),starter:roster.filter(p=>p.pos==='P').sort((a,b)=>overall(b)-overall(a))[0].id,tactic:'balanced',training:'balanced',staff:coachPool().filter(c=>c.id.endsWith('-0')),standings:Object.fromEntries(leagues.map(l=>[l.id,clubs.filter(c=>c.league===l.id).map(c=>({club:c.id,w:0,l:0,d:0,rf:0,ra:0,form:[]}))])),history:[],news:[],deals:[],ownership:{},transferred:[],past:[],phase:'regular',series:[],champion:'',reputation:getLeague(league).level,income:0,expenses:0};news(g,`${getClub(club).name}, ${g.manager} 감독 선임`,'구단의 새 시즌이 시작됩니다. 타순과 선발을 확인하고 첫 경기에 나서세요.');news(g,'스카우팅 리포트 도착','세계 선수 시장에서 실명 선수와 가상 유망주를 확인할 수 있습니다. 에이전트에게 계약 조건을 제안하세요.','scout');return g;}
export function pairings(league:string,day:number){const ids=clubs.filter(c=>c.league===league).map(c=>c.id);if(ids.length%2)ids.push('bye');const n=ids.length,round=day%(n-1),cycle=Math.floor(day/(n-1));for(let i=0;i<round;i++)ids.splice(1,0,ids.pop()!);const pairs:string[][]=[];for(let i=0;i<n/2;i++){let pair=[ids[i],ids[n-1-i]];if((round+i+cycle)%2)pair=pair.reverse();if(!pair.includes('bye'))pairs.push(pair);}return pairs;}
export function nextFixture(g:GameState){if(g.phase==='finished')return null;if(g.phase!=='regular'){const target=g.phase==='semifinal'?2:3;const s=g.series.find(s=>(s.a===g.club||s.b===g.club)&&s.aw<target&&s.bw<target);return s?((s.aw+s.bw)%2?[s.b,s.a]:[s.a,s.b]):null;}return pairings(getClub(g.club).league,g.day).find(p=>p.includes(g.club))||null;}
function teamStrength(g:GameState,id:string){const r=rosterFor(g,id);return r.reduce((s,p)=>s+overall(p),0)/(r.length||1);}
function doMatch(g:GameState,home:string,away:string,random:()=>number,post=false):Result{const involved=home===g.club||away===g.club;const rosters=[rosterFor(g,away),rosterFor(g,home)];const lineups=rosters.map((r,i)=>{const club=i?home:away;const ids=club===g.club?g.lineup:lineupAuto(r);return ids.map(id=>r.find(p=>p.id===id)!).filter(Boolean);});const pitchers=rosters.map((r,i)=>{const id=i?home:away;return id===g.club?r.find(p=>p.id===g.starter)!:r.filter(p=>p.pos==='P').sort((a,b)=>overall(b)-overall(a))[g.day%Math.min(5,r.filter(p=>p.pos==='P').length)];});const score=[0,0],hits=[0,0],errors=[0,0],innings:(number|null)[][]=[[],[]],log:Result['log']=[];const order=[0,0];const performance=new Map<string,number>();
 const pitchStats=[blankStats(),blankStats()];
 for(let inn=1;inn<=30;inn++){
  for(let side=0;side<2;side++){
   if(inn>=9&&side===1&&score[1]>score[0]){innings[1].push(null);break;}
   const before=score[side];let outs=0;const bases:(Player|null)[]=[null,null,null];if(inn>9&&getClub(home).league==='mlb')bases[1]=lineups[side][(order[side]+8)%9];let appearances=0;
   const ownBat=(side?home:away)===g.club;const ownPitch=(side?away:home)===g.club;const pitcher=pitchers[1-side];const pStrength=overall(pitcher)*(0.75+pitcher.condition/400)+(ownPitch?(coachSkill(g,'투수')-50)/6:0);const defense=rosters[1-side].filter(p=>p.pos!=='P').reduce((s,p)=>s+p.field,0)/Math.max(1,rosters[1-side].filter(p=>p.pos!=='P').length)+(ownPitch?(coachSkill(g,'수비')-50)/5:0);
   while(outs<3&&appearances++<120){const p=lineups[side][order[side]++%lineups[side].length];const stats=ownBat?p.stats:blankStats();let runs=0;let event='';let isOut=false;const cond=.7+p.condition*.003;const bonus=ownBat?(coachSkill(g,'타격')-50)*.0008:0;const contact=clamp(.24+(p.contact*cond-pStrength)*.0028+bonus,.10,.43);const aggressive=ownBat&&g.tactic==='power';const patient=ownBat&&g.tactic==='patient';const smallball=ownBat&&g.tactic==='smallball';const roll=random();
    if(roll<clamp(.073+(70-pitcher.control)*.0009+(patient?.027:0),.035,.14)){stats.bb++;if(bases[0]){if(bases[1]){if(bases[2])runs++;bases[2]=bases[1];}bases[1]=bases[0];}bases[0]=p;event='볼넷';}
    else if(roll<.08+contact+(aggressive?-.015:0)){
     stats.ab++;stats.h++;hits[side]++;const extra=random();const hrChance=clamp(.10+(p.power-pStrength)*.003+(aggressive?.07:0),.03,.33);const advance=extra<hrChance?4:extra<hrChance+.015?3:extra<hrChance+.22?2:1;
     if(advance===4){runs=1+bases.filter(Boolean).length;bases.fill(null);stats.hr++;event='홈런';}else{for(let b=2;b>=0;b--)if(bases[b]){let move=advance;if(advance===1&&b===1&&random()<(bases[b]!.speed/160))move=2;if(b+move>=3)runs++;else bases[b+move]=bases[b];bases[b]=null;}bases[advance-1]=p;event=advance===1?'안타':advance===2?'2루타':'3루타';}
    }else if(random()<clamp((75-defense)*.001+.012,.004,.05)){stats.ab++;if(bases[2])runs++;bases[2]=bases[1];bases[1]=bases[0];bases[0]=p;errors[1-side]++;event='수비 실책 출루';}
    else{stats.ab++;outs++;isOut=true;pitchStats[1-side].outs++;if(random()<.36+(aggressive?.08:0)){stats.k++;event='삼진';}else{event='범타';if(bases[0]&&outs<3&&random()<.15){outs++;pitchStats[1-side].outs++;bases[0]=null;event='병살타';}else if(bases[2]&&outs<3&&random()<.22){runs++;bases[2]=null;event='희생 타점';}}}
    if(smallball&&bases[0]&&!bases[1]&&outs<3&&random()<.20){if(random()<clamp(bases[0]!.speed/105,.3,.92)){bases[1]=bases[0];bases[0]=null;event+=' · 2루 도루';}else{bases[0]=null;outs++;pitchStats[1-side].outs++;event+=' · 도루 실패';}}
    score[side]+=runs;stats.rbi+=runs;pitchStats[1-side].er+=runs;performance.set(p.name,(performance.get(p.name)||0)+(isOut?0:1)+runs*2);
    if(involved&&(!isOut||runs>0||outs>=3))log.push({inning:inn,half:side,text:`${p.name} ${event}${runs?` · ${runs}타점`:''}`,score:[...score]});
    if(inn>=9&&side===1&&score[1]>score[0])break;
   }
   innings[side].push(score[side]-before);
  }
  if(inn>=9&&score[0]!==score[1])break;
  if(!post&&inn>=12)break;
 }
 // Postseason games continue through a bounded sudden-death tiebreak inning.
 if(post&&score[0]===score[1]){const side=random()<.5?0:1;score[side]++;innings[0].push(side===0?1:0);innings[1].push(side===1?1:0);log.push({inning:innings[0].length,half:side,text:'승부치기 결승 득점',score:[...score]});}
 if(involved){const side=home===g.club?1:0;const ownPitch=pitchers[side];ownPitch.stats.g++;ownPitch.stats.outs+=pitchStats[side].outs;ownPitch.stats.er+=pitchStats[side].er;if(score[side]>score[1-side])ownPitch.stats.wins++;ownPitch.condition=clamp(ownPitch.condition-52,20,100);for(const p of lineups[side]){p.stats.g++;p.condition=clamp(p.condition-6,25,100);}}
 return {id:`${g.year}-${g.day}-${home}-${away}`,day:g.day,home,away,homeScore:score[1],awayScore:score[0],innings,hits,errors,log,mvp:[...performance].sort((a,b)=>b[1]-a[1])[0]?.[0]||'',post};}
function record(g:GameState,res:Result,league:string){for(const side of [0,1]){const id=side?res.home:res.away;const s=g.standings[league].find(s=>s.club===id)!;const runs=side?res.homeScore:res.awayScore,against=side?res.awayScore:res.homeScore;const letter=runs===against?'D':runs>against?'W':'L';s.rf+=runs;s.ra+=against;if(letter==='W')s.w++;else if(letter==='L')s.l++;else s.d++;s.form=[...s.form,letter].slice(-5);}}
export function advance(g:GameState,count=1){if(g.phase==='finished')throw new Error('시즌이 종료됐습니다. 다음 시즌을 시작해 주세요.');const r=rng(g.seed);for(let n=0;n<clamp(count,1,14)&&g.phase!=='finished';n++){
 const ownLeague=getClub(g.club).league;
 if(g.phase==='regular'){
  for(const l of leagues){const elapsed=Math.floor(g.day/g.rounds* (g.mode==='full'?l.games:Math.max(6,(clubs.filter(c=>c.league===l.id).length-1)*2)));const until=l.id===ownLeague?elapsed+1:Math.floor((g.day+1)/g.rounds*(g.mode==='full'?l.games:Math.max(6,(clubs.filter(c=>c.league===l.id).length-1)*2)));
   const roundsToPlay=l.id===ownLeague?[g.day]:Array.from({length:Math.max(0,until-elapsed)},(_,k)=>elapsed+k);
   for(const day of roundsToPlay)for(const [home,away] of pairings(l.id,day)){
    const involved=home===g.club||away===g.club;let res:Result;
    if(involved)res=doMatch(g,home,away,r);else{const a=teamStrength(g,home),b=teamStrength(g,away);const poisson=(mean:number)=>{let p=1,k=0;do{k++;p*=r();}while(p>Math.exp(-mean)&&k<30);return k-1;};let hs=poisson(clamp(4.2+(a-b)*.08,1,8)),as=poisson(clamp(4+(b-a)*.08,1,8));if(hs===as&&r()<.8){if(r()<.5)hs++;else as++;}res={id:`${g.year}-${g.day}-${home}`,day:g.day,home,away,homeScore:hs,awayScore:as,innings:[],hits:[],errors:[],log:[],mvp:''};}
    record(g,res,l.id);if(involved)afterMatch(g,res);
   }
  }
 }else{
  const target=g.phase==='semifinal'?2:3;
  for(const s of g.series){if(s.aw>=target||s.bw>=target)continue;const [home,away]=(s.aw+s.bw)%2?[s.b,s.a]:[s.a,s.b];const res=doMatch(g,home,away,r,true);const winner=res.homeScore>res.awayScore?home:away;if(winner===s.a)s.aw++;else s.bw++;if(home===g.club||away===g.club)afterMatch(g,res);}
  if(g.series.every(s=>s.aw>=target||s.bw>=target)){const winners=g.series.map(s=>s.aw>=target?s.a:s.b);if(g.phase==='semifinal'){g.phase='final';g.series=[{a:winners[0],b:winners[1],aw:0,bw:0}];news(g,'챔피언십 대진 확정',`${getClub(winners[0]).name} vs ${getClub(winners[1]).name} · 5전 3선승제`,'league');}else{g.phase='finished';g.champion=winners[0];const rank=standings(g).findIndex(s=>s.club===g.club)+1;const own=g.standings[ownLeague].find(s=>s.club===g.club)!;g.past.push({year:g.year,rank,w:own.w,l:own.l,champion:g.champion});const prize=g.champion===g.club?teamBudget(ownLeague)*.25:teamBudget(ownLeague)*.04;g.budget+=prize;g.income+=prize;g.reputation=clamp(g.reputation+(g.champion===g.club?4:rank<=4?2:-1),40,99);news(g,`${getClub(g.champion).name}, 시즌 우승!`,`${g.year} 시즌이 끝났습니다. 상금 ${money(prize)}이 입금됐습니다.`,'league');}}
 }
 g.day++;for(const p of g.roster){p.condition=clamp(p.condition+4+coachSkill(g,'체력')*.09+(g.training==='rest'?9:g.training==='intense'?-5:0),20,100);if(g.training!=='rest'&&p.age<31&&r()<.08){const skill=(g.training==='pitching'||g.training==='balanced'&&p.pos==='P')?'stuff':g.training==='defense'?'field':g.training==='power'?'power':'contact';const role=skill==='stuff'?'투수':skill==='field'?'수비':'타격';if(p[skill]<p.potential)p[skill]=clamp(p[skill]+(coachSkill(g,role)/140),20,p.potential);}}
 const salary=(g.roster.reduce((s,p)=>s+p.salary,0)+g.staff.reduce((s,c)=>s+c.salary,0))/g.rounds;g.budget-=salary;g.expenses+=salary;
 const starter=g.roster.filter(p=>p.pos==='P').sort((a,b)=>b.condition*overall(b)-a.condition*overall(a))[0];g.starter=starter.id;
 if(g.day%7===0)news(g,'주간 훈련 리포트',`선수단 평균 컨디션 ${Math.round(g.roster.reduce((s,p)=>s+p.condition,0)/g.roster.length)}%. 코치진의 훈련이 선수 성장에 반영됐습니다.`,'training');
 if(g.phase==='regular'&&g.day>=g.rounds){const top=standings(g).slice(0,4);g.phase='semifinal';g.series=[{a:top[0].club,b:top[3].club,aw:0,bw:0},{a:top[1].club,b:top[2].club,aw:0,bw:0}];news(g,'포스트시즌 개막','상위 4개 구단이 3전 2선승 준결승에 진출했습니다. 결승은 5전 3선승입니다.','league');break;}
 }g.seed=Math.floor(r()*4294967295);return g;}
function afterMatch(g:GameState,res:Result){g.history.unshift(res);g.history=g.history.slice(0,180);const home=res.home===g.club;const own=home?res.homeScore:res.awayScore,opp=home?res.awayScore:res.homeScore;const earned=teamBudget(getClub(g.club).league)*(home?.020:.004)*(own>opp?1.15:1);g.budget+=earned;g.income+=earned;news(g,`${own===opp?'무승부':own>opp?'승리':'패배'} · ${getClub(res.away).short} ${res.awayScore} : ${res.homeScore} ${getClub(res.home).short}`,`경기 MVP ${res.mvp} · 경기 수입 ${money(earned)}`,'match');}
export function agentFor(p:Player){const i=hash(p.id)%5;return [{name:'박준혁',agency:'BASE Sports',fee:.05,priority:'안정적인 장기 계약'},{name:'Daniel Cruz',agency:'Diamond Agency',fee:.08,priority:'연봉 우선'},{name:'사토 켄지',agency:'Next Inning',fee:.06,priority:'출전 기회'},{name:'Alex Morgan',agency:'Northstar Sports',fee:.10,priority:'상위 리그 진출'},{name:'이수민',agency:'HOME PLATE',fee:.04,priority:'선수 성장'}][i];}
export function askPrice(p:Player){return p.club==='fa'?0:Math.round(p.salary*(1.2+p.years*.45)+(p.potential-overall(p))*3);}
export function negotiate(g:GameState,playerId:string,salary:number,years:number,type:'buy'|'renew'='buy') {const p=type==='renew'?g.roster.find(p=>p.id===playerId):marketPlayers(g).find(p=>p.id===playerId);if(!p)throw new Error('해당 선수를 찾을 수 없습니다.');if(!Number.isFinite(salary)||salary<=0||years<1||years>5||!Number.isInteger(years))throw new Error('유효한 연봉과 1~5년 계약을 입력해 주세요.');const agent=agentFor(p);const gap=Math.max(0,overall(p)-g.reputation-4);const demand=Math.max(5,Math.round(p.salary*(1.04+gap*.03)));const fee=type==='renew'?0:askPrice(p);const required=fee+salary*agent.fee+salary*.15;const willing=gap<18||salary>=demand*1.3;let status:Deal['status']=salary>=demand&&(years>=2||salary>=demand*1.1)&&willing?'accepted':salary>=demand*.65?'counter':'rejected';if(required>g.budget)status='rejected';const offered=status==='counter'?Math.round(demand*(years===1?1.1:1)):salary;const deal:Deal={id:`deal-${g.year}-${g.day}-${g.deals.length}-${playerId}`,player:p,type,salary:offered,years:status==='counter'?Math.max(2,years):years,fee,agentFee:Math.round(offered*agent.fee),status,message:required>g.budget?'계약금과 이적료를 감당할 예산이 부족합니다.':status==='accepted'?'조건에 동의합니다. 최종 서명하면 계약이 완료됩니다.':status==='counter'?`${agent.name}의 역제안: 연봉 ${money(offered)}, ${Math.max(2,years)}년 계약을 원합니다.`:'현재 제안은 선수의 기대 조건에 미치지 못합니다.',day:g.day};g.deals=g.deals.filter(d=>d.player.id!==p.id);g.deals.unshift(deal);g.deals=g.deals.slice(0,30);news(g,`${p.name} · 계약 ${status==='accepted'?'합의':status==='counter'?'역제안':'거절'}`,deal.message,'transfer');return g;}
export function signDeal(g:GameState,id:string){const d=g.deals.find(d=>d.id===id);if(!d||d.status==='rejected')throw new Error('유효한 계약 제안이 없습니다.');if(g.day-d.day>14)throw new Error('제안 유효기간이 지났습니다. 다시 협상해 주세요.');const cash=d.fee+d.agentFee+d.salary*.15;if(g.budget<cash)throw new Error('영입 예산이 부족합니다.');if(d.type==='buy'&&g.roster.length>=85)throw new Error('선수단 정원 85명입니다. 매각 후 영입해 주세요.');if(d.type==='buy'&&g.roster.some(p=>p.id===d.player.id))throw new Error('이미 소속된 선수입니다.');g.budget-=cash;g.expenses+=cash;const p={...d.player,club:g.club,salary:d.salary,years:d.years,condition:100,stats:d.type==='buy'?blankStats():d.player.stats};if(d.type==='renew')g.roster=g.roster.map(old=>old.id===p.id?p:old);else{g.roster.push(p);g.ownership[p.id]=g.club;g.transferred=(g.transferred||[]).filter(v=>v.id!==p.id);}g.deals=g.deals.filter(old=>old.player.id!==p.id);news(g,`${p.name} ${d.type==='buy'?'영입':'재계약'} 완료`,`${d.years}년 · 연봉 ${money(d.salary)} · 에이전트 ${agentFor(p).name}`,'transfer');return g;}
export function sellPlayer(g:GameState,id:string){const p=g.roster.find(p=>p.id===id);if(!p)throw new Error('선수를 찾을 수 없습니다.');if(g.roster.length<=20)throw new Error('선수단은 최소 20명이 필요합니다.');const same=g.roster.filter(v=>v.pos===p.pos).length;const min={P:5,C:1,IF:4,OF:3,DH:0}[p.pos];if(same<=min)throw new Error(`${p.pos} 포지션 선수가 부족해 매각할 수 없습니다.`);const fee=Math.round(askPrice(p)*.7);g.budget+=fee;g.income+=fee;const dest=clubs.filter(c=>c.id!==g.club)[hash(p.id+g.year)% (clubs.length-1)];g.ownership[p.id]=dest.id;g.transferred=(g.transferred||[]).filter(v=>v.id!==p.id);g.transferred.push({...p,club:dest.id});g.roster=g.roster.filter(v=>v.id!==id);g.lineup=lineupAuto(g.roster);if(g.starter===id)g.starter=g.roster.find(p=>p.pos==='P')!.id;g.deals=g.deals.filter(d=>d.player.id!==id);news(g,`${p.name} 이적 완료`,`${getClub(dest.id).name}으로 이적 · 수입 ${money(fee)}`,'transfer');return g;}
export function nextSeason(g:GameState){if(g.phase!=='finished')throw new Error('현재 시즌을 먼저 마쳐 주세요.');g.year++;const departed:string[]=[];for(const p of g.roster){p.age++;p.years--;p.condition=100;p.stats=blankStats();if(p.age>=34){p.contact=clamp(p.contact-1.5,20,99);p.power=clamp(p.power-1,20,99);p.speed=clamp(p.speed-2,20,99);p.stuff=clamp(p.stuff-1.5,20,99);}if(p.years<=0)departed.push(p.id);}
 g.transferred=[...(g.transferred||[]),...g.roster.filter(p=>p.years<=0).map(p=>({...p,club:'fa',years:1}))];g.roster=g.roster.filter(p=>p.years>0);for(const id of departed)g.ownership[id]='fa';const rookies=baseRoster(g.club,g.year).filter(p=>!p.real);let i=0;for(const [pos,min] of [['P',7],['C',2],['IF',6],['OF',4],['DH',1]] as [Pos,number][]){while(g.roster.filter(p=>p.pos===pos).length<min){const p=makePlayer(g.club,400+i++,undefined,g.year);p.pos=pos;if(pos==='P'){p.stuff=p.contact;p.control=p.field;}g.roster.push(p);}}g.roster.push(...rookies.slice(0,3).filter(p=>!g.roster.some(x=>x.id===p.id)));g.lineup=lineupAuto(g.roster);g.starter=g.roster.find(p=>p.pos==='P')!.id;g.day=0;g.phase='regular';g.series=[];g.champion='';g.history=[];g.deals=[];g.budget+=teamBudget(getClub(g.club).league)*.55;g.income=teamBudget(getClub(g.club).league)*.55;g.expenses=0;for(const l of leagues)for(const s of g.standings[l.id])Object.assign(s,{w:0,l:0,d:0,rf:0,ra:0,form:[]});news(g,`${g.year} 시즌 시작`,`${departed.length}명 계약 만료. 가상 신인 입단과 베테랑 노쇠화가 반영됐습니다.`,'league');return g;}
export function applyAction(g:GameState,a:Record<string,unknown>){const s=structuredClone(g);switch(a.type){case'advance':return advance(s,Number(a.count)||1);case'auto':s.lineup=lineupAuto(s.roster);return s;case'lineup':{const ids=a.ids as string[];if(!Array.isArray(ids)||ids.length!==9||new Set(ids).size!==9||ids.some(id=>!s.roster.some(p=>p.id===id&&p.pos!=='P')))throw new Error('타순에는 서로 다른 타자 9명이 필요합니다.');const ps=ids.map(id=>s.roster.find(p=>p.id===id)!);if(!ps.some(p=>p.pos==='C')||ps.filter(p=>p.pos==='IF').length<4||ps.filter(p=>p.pos==='OF').length<3)throw new Error('포수 1명, 내야수 4명, 외야수 3명이 필요합니다.');s.lineup=ids;return s;}case'starter':if(!s.roster.some(p=>p.id===a.id&&p.pos==='P'))throw new Error('투수를 선택해 주세요.');s.starter=String(a.id);return s;case'tactic':if(!['balanced','power','smallball','patient'].includes(String(a.value)))throw new Error('전술을 확인해 주세요.');s.tactic=String(a.value);return s;case'training':if(!['balanced','power','pitching','defense','rest'].includes(String(a.value)))throw new Error('훈련을 확인해 주세요.');s.training=String(a.value);return s;case'negotiate':return negotiate(s,String(a.id),Number(a.salary),Number(a.years),a.renew?'renew':'buy');case'sign':return signDeal(s,String(a.id));case'sell':return sellPlayer(s,String(a.id));case'coach':{const c=coachPool(s.year).find(c=>c.id===a.id);if(!c)throw new Error('코치를 찾을 수 없습니다.');if(s.staff.some(x=>x.id===c.id))throw new Error('이미 선임된 코치입니다.');const cost=c.salary*.5;if(s.budget<cost)throw new Error('코치 선임 예산이 부족합니다.');s.budget-=cost;s.expenses+=cost;s.staff=s.staff.filter(old=>old.role!==c.role);s.staff.push(c);news(s,`${c.name} ${c.role} 코치 선임`,`능력 ${c.skill} · 연봉 ${money(c.salary)} · ${c.style}`,'training');return s;}case'nextSeason':return nextSeason(s);default:throw new Error('지원하지 않는 요청입니다.');}}
