'use client';
import {
  Activity,
  ArrowUpRight,
  ClipboardList,
  Globe2,
  Handshake,
  House,
  Users,
  Wallet,
  CalendarDays,
  MessageSquare,
  GraduationCap,
  Binoculars,
  CircleDot,
  Mic,
} from 'lucide-react';

export const nav = [
  ...[
    { id: 'manager-contract', label: '감독 계약' },
    { id: 'manager-history', label: '감독 경력' },
    { id: 'job-security', label: '직업 안정성' },
    { id: 'job-offers', label: '면접 · 계약 제안' },
    { id: 'vision', label: '구단 비전' },
    { id: 'medical', label: '의무 센터' },
    { id: 'trade', label: '트레이드' },
    { id: 'draft', label: '신인 선발' },
  ].map((n) => ({ ...n, icon: ClipboardList })),
  { id: 'records', label: '통산 기록 · 은퇴 선수', icon: ClipboardList },
  { id: 'jobs', label: '채용 센터', icon: Handshake },
  { id: 'manager', label: '내 프로필', icon: Handshake },
  { id: 'home', label: '홈', icon: House },
  { id: 'inbox', label: '수신함', icon: MessageSquare },
  { id: 'matchday', label: '경기 준비', icon: CircleDot },
  { id: 'match', label: '경기장', icon: CircleDot },
  { id: 'media', label: '인터뷰 · 팀 대화', icon: Mic },
  { id: 'dynamics', label: '선수단 분위기', icon: Activity },
  { id: 'squad', label: '선수단', icon: Users },
  { id: 'reserves', label: '1군 · 2군 관리', icon: GraduationCap },
  { id: 'registrations', label: '등록 · 말소', icon: ClipboardList },
  { id: 'training', label: '훈련', icon: GraduationCap },
  { id: 'tactics', label: '전술 · 타순', icon: ClipboardList },
  { id: 'schedule', label: '일정 · 결과', icon: CalendarDays },
  { id: 'world', label: '리그 · 세계', icon: Globe2 },
  { id: 'market', label: '영입 · 이적', icon: ArrowUpRight },
  { id: 'scouting', label: '스카우트', icon: Binoculars },
  { id: 'agents', label: '에이전트', icon: Handshake },
  { id: 'staff', label: '스태프', icon: GraduationCap },
  { id: 'finance', label: '구단 재정', icon: Wallet },
];
