export type Pos = 'P' | 'C' | 'IF' | 'OF' | 'DH';
export type Stats = {
  ab: number;
  h: number;
  hr: number;
  rbi: number;
  bb: number;
  k: number;
  outs: number;
  er: number;
  wins: number;
  g: number;
  saves?: number;
  holds?: number;
  hrAllowed?: number;
};
export type Player = {
  id: string;
  name: string;
  original: string;
  club: string;
  pos: Pos;
  age: number;
  real: boolean;
  country: string;
  number: number;
  contact: number;
  power: number;
  speed: number;
  field: number;
  stuff: number;
  control: number;
  potential: number;
  condition: number;
  marketValue?: number;
  salary: number;
  years: number;
  stats: Stats;
  squad?: 'first' | 'reserve';
  familiarity?: Partial<Record<DefensivePosition, number>>;
  positionTraining?: DefensivePosition;
  reserveStats?: Stats;
  source?: string;
  ageEstimated?: boolean;
  rating?: RatingEvidence;
  mood?: PlayerMood;
};
export type Coach = {
  id: string;
  name: string;
  role: string;
  skill: number;
  salary: number;
  style: string;
  real?: boolean;
  sourceClub?: string;
  source?: string;
  verifiedRole?: string;
};
export type Standing = {
  club: string;
  w: number;
  l: number;
  d: number;
  rf: number;
  ra: number;
  form: string[];
};
export type Result = {
  id: string;
  day: number;
  home: string;
  away: string;
  homeScore: number;
  awayScore: number;
  innings: (number | null)[][];
  hits: number[];
  errors: number[];
  log: { inning: number; half: number; text: string; score: number[]; play?: ReplayPlay }[];
  replayTeams?: [ReplayTeam, ReplayTeam];
  mvp: string;
  post?: boolean;
  friendly?: boolean;
  date?: string;
  fixtureId?: string;
};
export type Deal = {
  id: string;
  player: Player;
  type: 'buy' | 'renew';
  salary: number;
  years: number;
  fee: number;
  agentFee: number;
  status: 'accepted' | 'counter' | 'rejected';
  message: string;
  day: number;
  year?: number;
  seller?: SellerDecision;
};
export type GameState = {
  version: 1;
  year: number;
  day: number;
  club: string;
  manager: string;
  budget: number;
  seed: number;
  rounds: number;
  mode: 'short' | 'full';
  roster: Player[];
  lineup: string[];
  starter: string;
  tactic: string;
  training: string;
  staff: Coach[];
  standings: Record<string, Standing[]>;
  history: Result[];
  news: NewsItem[];
  deals: Deal[];
  ownership: Record<string, string>;
  transferred: Player[];
  past: { year: number; rank: number; w: number; l: number; champion: string }[];
  phase: 'preseason' | 'regular' | 'semifinal' | 'final' | 'finished';
  series: { a: string; b: string; aw: number; bw: number }[];
  champion: string;
  reputation: number;
  income: number;
  expenses: number;
  rules?: {
    firstSeasonTransferBan: boolean;
    startYear: number;
    preseason: boolean;
    revealPotential?: boolean;
  };
  defense?: Defense;
  tacticFamiliarity?: number;
  instructions?: TeamInstructions;
  tacticBook?: SavedTactic[];
  reserve?: { w: number; l: number; d: number; history: ReserveResult[] };
  saleOffers?: SaleOffer[];
  transferListed?: Record<string, number>;
  worldResults?: Result[];
  catalogVersion?: string;
  pitching?: PitchingPlan;
  liveMatch?: LiveMatch;
  calendar?: { openingDate: string; startDay: number; remaining?: Record<string, number> };
};
export type League = {
  id: string;
  name: string;
  country: string;
  flag: string;
  region: string;
  label: string;
  games: number;
  level: number;
  source: string;
  season: string;
};
export type Club = {
  id: string;
  name: string;
  short: string;
  league: string;
  color: string;
  city: string;
  division: string;
};
export type RealSeed = {
  name: string;
  pos: string;
  age: number;
  number?: number;
  country?: string;
  rating?: number;
  ageEstimated?: boolean;
  source?: string;
};
export type Agent = { id: string; name: string; agency: string; fee: number; priority: string };
export type WorldCatalog = {
  version: string;
  year: number;
  leagues: League[];
  clubs: Club[];
  players: Player[];
  agents: Agent[];
  coaches: Coach[];
  rosterNote: string;
  fixtures?: Fixture[];
};
export type FinanceEntry = {
  id: string;
  revision: number;
  year: number;
  day: number;
  kind: string;
  amount: number;
  balance: number;
  createdAt: string;
};

export type DefensivePosition = 'P' | 'C' | '1B' | '2B' | '3B' | 'SS' | 'LF' | 'CF' | 'RF' | 'DH';
export type Defense = Record<DefensivePosition, string>;
export type TeamInstructions = { steal: number; patience: number; power: number; depth: number };
export type SavedTactic = {
  id: string;
  name: string;
  tactic: string;
  lineup: string[];
  starter: string;
  defense: Defense;
  instructions: TeamInstructions;
  pitching?: PitchingPlan;
};
export type ReserveResult = {
  day: number;
  opponent: string;
  own: number;
  against: number;
  played: string[];
};

export type ReplayState = { outs: number; bases: (string | null)[]; score: number[] };
export type ReplayPlay = {
  batter: string;
  pitcher: string;
  before: ReplayState;
  after: ReplayState;
  steal?: { runner: string; safe: boolean };
};
export type ReplayTeam = {
  lineup: string[];
  defense: Defense;
  players: { id: string; name: string; number: number }[];
};

export type PerformanceRecord = {
  name: string;
  league: string;
  season: number;
  kind: 'bat' | 'pitch';
  source: string;
  officialId?: string;
  club?: string;
  team?: string;
  ambiguous?: boolean;
  pa?: number;
  ab?: number;
  h?: number;
  hr?: number;
  tb?: number;
  bb?: number;
  k?: number;
  sb?: number;
  g?: number;
  outs?: number;
  er?: number;
  cs?: number;
  hbp?: number;
  sf?: number;
  gdp?: number;
  obp?: number;
  slg?: number;
  gs?: number;
  sv?: number;
  hld?: number;
};
export type RatingEvidence = {
  version: string;
  status: 'rated' | 'provisional' | 'missing';
  season: number;
  source?: string;
  record?: PerformanceRecord;
  method: string;
  estimatedAttributes: string[];
  base: Partial<
    Record<'contact' | 'power' | 'speed' | 'field' | 'stuff' | 'control' | 'potential', number>
  >;
};

export type Fixture = {
  id: string;
  date: string;
  home: string;
  away: string;
  league: string;
  time?: string;
  source?: string;
  generated?: boolean;
};

export type PlayerMood = {
  value: number;
  role: 'core' | 'regular' | 'rotation' | 'prospect';
  reason: string;
  recent: boolean[];
  lastPlayedDay?: number;
  lastConcernDay?: number;
  promise?: { due: number; games: number; startGames: number };
};
export type NewsItem = {
  id: string;
  year?: number;
  day: number;
  date?: string;
  title: string;
  body: string;
  kind: string;
  read?: boolean;
  playerId?: string;
  choiceKind?: 'playingTime';
  choice?: string;
  response?: string;
};
export type SellerDecision = {
  club: string;
  status: 'accepted' | 'counter' | 'refused';
  role: string;
  fee: number;
  reason: string;
};
export type SaleOffer = {
  id: string;
  playerId: string;
  club: string;
  fee: number;
  day: number;
  expires: number;
  year: number;
};

export type PitchingPlan = { rotation: string[]; bullpen: string[]; closer: string; next: number };
export type LiveMatch = {
  home: string;
  away: string;
  seed: number;
  cursor: number;
  finished: boolean;
  result: Result;
  opponents?: Player[][];
};
